[package]
name = "topiary-client-app"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "^1.28.1", features = ["rt-multi-thread", "macros"] }
topiary = { path = "../../topiary-core" }
